#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("heavykick.Resource", IsApplication=true)]

namespace heavykick
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_180hemispheres = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_180x101 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_180x160_3dv = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_180x180 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_180x180_3dh = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_180x180_3dv = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_180x180_squished_3dh = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_3dh = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_3dv = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic__2dp = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic__3dph = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic__3dpv = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic__planetarium = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ic__rtxp = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ic__v360 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int ic_cylinder_slice_16x9_3dv = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int ic_cylinder_slice_2x25_3dv = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int ic_nothing = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int ic_sib3d = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int Icon = 2130837523;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050009
			public const int AudioOption = 2131034121;
			
			// aapt resource value: 0x7f050000
			public const int Edit = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int LinkPreview = 2131034115;
			
			// aapt resource value: 0x7f050007
			public const int MilkVROptions = 2131034119;
			
			// aapt resource value: 0x7f050001
			public const int MyButton = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int button1 = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int lblUrl = 2131034114;
			
			// aapt resource value: 0x7f050006
			public const int linearLayout2 = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int radioButton1 = 2131034120;
			
			// aapt resource value: 0x7f05000a
			public const int radioButton2 = 2131034122;
			
			// aapt resource value: 0x7f050005
			public const int scrollView1 = 2131034117;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Second = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int AudioFormat = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int ButtonStartCaption = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int TestLaunch = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
